services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile.dev
        container_name: content-hub-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - content-hub

    db:
        image: postgres:15
        container_name: content-hub-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5433:${DB_PORT}"
        volumes:
            - content-hub:/var/lib/postgresql/data
        networks:
            - content-hub

    nginx:
        image: nginx:alpine
        container_name: content-hub-nginx
        ports:
            - "${APP_PORT}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - content-hub

volumes:
    content-hub:

networks:
    content-hub:
